### PR TITLE
Translate to Japanese 01-Navigation (2, 3)

### PR DESCRIPTION
**Pull request by sun-flat-yamada**
# Summary

- This is the Japanese localized version of 01-Navigation.
  - 2-Navigate_to_definition
  - 3-Navigate_to_somewhere_youve_already_been

__NOTE__
- I found a few things that do not work as per the workshop with the latest ReSharper and Rider.
  - Bookmarks, and View Recent Edits.
- It appears to be a problem on the tool side, so I have left it as a TODO comment.

# Issue

https://github.com/JetBrains/resharper-rider-samples/issues/20
Proposal for creating a Japanese localized version 

# How did I test it?

- I have only conducted self-verification using a translation tool.
- If you have a reliable Japanese person, I would like to ask for a third-party review.

__NOTE__
- Some parts have been "free/loose translation".
- I have filled in the gaps between the lines from a Japanese developer's point of view and translated them into what I consider to be more appropriate expressions.

Pleasure!

### CODE REVIEW

**Comment by maartenba** [comment]
Regarding those TODO's, what issues are you encountering?
Just tried a couple of these (recent edits) in VS+R# and those seem to work fine?

**Comment by sun-flat-yamada** [comment]
Hello, @maartenba .

> Regarding those TODO's, what issues are you encountering?
> Just tried a couple of these (recent edits) in VS+R# and those seem to work fine?

There are three problems in total on my environment. I'll explain each of them.


## Problems @ ReSharper 2021.1 on VisualStudio 2019

There are two problems in my environment :

1. Bookmarks is not worked (Shortcuts are not assigned)
2. View Recent Edits is not worked (Shortcuts are not assigned)


### 1. Bookmarks is not worked (Shortcuts are not assigned)

I use the VisualStudio style setting in the ReSharper options (I also changed it to IntelliJ style once and then changed it back to VisualStudio style again).

jetbrains-resharper-options

However, Ctrl+F11 will not work as a bookmark. I checked the shortcut assignments and found that they were not assigned.

jetbrains-resharper-not-assigned-bookmarks


### 2. View Recent Edits is not worked (Shortcuts are not assigned)

I still use the VisualStudio style setting.

However, `Ctrl+Shift+,` will not work as a `Recently Changed Files` . I checked the shortcut assignments and found that they were not assigned.

jetbrains-resharper-not-assigned-recently-edits


## Problems @ Rider 2021.1.2

There are one problem in my environment :

1. The behavior of the Recent Edits is different from the expectation stated in the workshop.


### 1. The behavior of the Recent Edits is different from the expectation stated in the workshop.

It says "Shows code blocks, not files" there, but when I press Ctrl+E twice to bring up the edit list, all I get is the file list (at 3.3-Recently_changed_files.cs).

Is my understanding of what you are talking about in the workshop incorrect?

jetbrains-rider-recently-edits

**Comment by maartenba** [comment]
Thanks for clarifying!

It's strange, ReSharper does have these keys assigned on my machine. (and Ctrl+Shift+, and Ctrl+F11 work as expected) Could you try once more?
* In Visual Studio options, find **Environment \| Keyboard**, then click "Reset"
* Go to ReSharper options and apply a keyboard scheme

For Rider, it should show you this: (recent edits with Ctrl+Shift+E in Rider keymap)
image

**Comment by sun-flat-yamada** [comment]
Thank you for your explanation, @maartenba .
I was able to confirm.

## On ReSharper

Unfortunately, it did not solve the problem.
I did the steps you taught me, but the key assignment was not changed.
Umm...


## On Rider

I was able to solve this one. I had mistakenly perceived different functions.

The file name is "3.3-Recently_changed_files.cs", which I think is inappropriate.
"Ctrl+E" is a function of "Recent Files", but this workshop provides "Recent locations".
This is "Ctrl+Shift+E". And this one's what this workshop expects.

I suggest you change it to "3.3-Recent_edits.cs".
(I will edit this file name in next PR.)

**Comment by maartenba** [comment]
Looks good, thanks once more!

**Pull request merged**
