### PR TITLE
(#20) Translate into Japanese @ 01-Navigation/4-Contextual_navigation

### PR DESCRIPTION
**Pull request by sun-flat-yamada**
# Summary

- This is the Japanese localized version of `01-Navigation/4-Contextual_navigation` .

# Issue

https://github.com/JetBrains/resharper-rider-samples/issues/20
Proposal for creating a Japanese localized version 

# How did I test it?

- I have only conducted self-verification using a translation tool.
- If you have a reliable Japanese person, I would like to ask for a third-party review.

__NOTE__
- Some parts have been "free/loose translation".
- I have filled in the gaps between the lines from a Japanese developer's point of view and translated them into what I consider to be more appropriate expressions.

Thanks.

### CODE REVIEW

**Comment by maartenba** [comment]
Looping in @khalidabuhakmeh who will review this one

**Comment by khalidabuhakmeh** [comment]
は、私にはよく見えますよ 👍 。 山田さん(@sun-flat-yamada )ありがとうございます.

**Comment by sun-flat-yamada** [comment]
@khalidabuhakmeh , I took your profile.
And, I didn't know you were working on learning Japanese!
I am also working on learning English now.

I'm not quite there yet, but I'll do my best.
If there is anything "creepy" in my expressions, please feel free to point it out.

Thank you for your continued support😄

**Comment by khalidabuhakmeh** [comment]
@sun-flat-yamada 😅 I'm trying to learn Japanese but at the rate that I'm learning, I don't know if I'll be good at conversational Japanese.

I think your English is excellent and thank you for helping.

**Pull request merged**
