### PR TITLE
Rename file name to adequately describes the content (Recent Edits)

### PR DESCRIPTION
**Pull request by sun-flat-yamada**
# Summary

- Rename file name to adequately describes the content.
- The following workshop contents are not "Recently changed files" but "Recent edits", so I renamed the files appropriately.

```
01-Navigation\3-Navigate_to_somewhere_youve_already_been\3.3-Recently_changed_files.cs
  -> 3.3-Recent_edits.cs
```

This topic is touched upon in the following discussion:

https://github.com/JetBrains/resharper-rider-samples/pull/28#issuecomment-831797780

# Issue

https://github.com/JetBrains/resharper-rider-samples/issues/30
Incorrect file name for "Recent Edits" workshop

https://github.com/JetBrains/resharper-rider-samples/issues/20
Proposal for creating a Japanese localized version 

# How did I test it?

- I have only conducted self-verification using a translation tool.
- If you have a reliable Japanese person, I would like to ask for a third-party review.

Good days!

### CODE REVIEW

**Comment by maartenba** [comment]
@sun-flat-yamada Would you mind making the change in the English version, too? That way we keep things consistent from the start.

**Comment by sun-flat-yamada** [comment]
> @ sun-flat-yamada英語版も変更していただけませんか。そうすれば、最初から一貫性を保つことができます。

Hi, @maartenba .

OK, of course. I'll set up an Issue and tie this PR to it.
I should have started an Issue first. I'm sorry about that.

Here is an issue :
#30 

I will update this PR (and I'll update English version soon).

**Comment by sun-flat-yamada** [comment]
@maartenba , I'm done.
Could you please check?

**Comment by maartenba** [comment]
Thanks @sun-flat-yamada !

**Pull request merged**
